#%RAML 0.8
---
title: ZBB File Automation
version: v1
                    
/files:
  description: Fetches every file in the source repository and then puts them in a target repository. Those files will be, at first, temporarily stored in Mulesfot. Once the Post operation is excecuted, they will be moved from Mulesoft to the target endpoint.


   
      
       